
================================================
Downloading HRRR Alaska
2018/02/02 12:35:24 Attempt 1/3 failed with 1 errors and: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f0780-005a74bd7c-1356d-default
2018/02/02 12:35:24 Attempt 2/3 failed with 1 errors and: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f0788-005a74bd7c-1356d-default
2018/02/02 12:35:24 Attempt 3/3 failed with 1 errors and: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f078c-005a74bd7c-1356d-default
2018/02/02 12:35:24 Failed to copy: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f078c-005a74bd7c-1356d-default
2018/02/02 12:35:24 Attempt 1/3 failed with 1 errors and: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f07b0-005a74bd7c-1356d-default
2018/02/02 12:35:24 Attempt 2/3 failed with 1 errors and: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f07b5-005a74bd7c-1356d-default
2018/02/02 12:35:24 Attempt 3/3 failed with 1 errors and: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f07bd-005a74bd7c-1356d-default
2018/02/02 12:35:24 Failed to copy: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f07bd-005a74bd7c-1356d-default
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/horel-group/archive_s3/HRRR_downloads/download_hrrrAK_multipro.py", line 247, in <module>
    p.map(download_hrrrAK_sfc, sfc_filenames)
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/multiprocessing/pool.py", line 227, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/uufs/chpc.utah.edu/sys/pkg/python/2.7.3_rhel6/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
OSError: [Errno 17] File exists: '/uufs/chpc.utah.edu/common/home/horel-group/archive/HRRR/alaska/sfc/20180202/'
2018/02/02 12:35:25 Attempt 1/3 failed with 1 errors and: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f07e5-005a74bd7d-1356d-default
2018/02/02 12:35:25 Attempt 2/3 failed with 1 errors and: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f07ea-005a74bd7d-1356d-default
2018/02/02 12:35:25 Attempt 3/3 failed with 1 errors and: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f07f1-005a74bd7d-1356d-default
2018/02/02 12:35:25 Failed to copy: InvalidLocationConstraint: The specified location-constraint is not valid
	status code: 400, request id: tx0000000000000001f07f1-005a74bd7d-1356d-default
Begin: 2018-02-02_12:35
End: 2018-02-02_12:35
ERROR: S3 error: 404 (NoSuchBucket)
